version: "3.9"
name: classified-ads

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: classified_ads
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
